SELECT 
FTR.FICHENO AS 'FIS_NO',FTR.DATE_ AS 'TARIH',YEAR(FTR.DATE_) AS 'YIL',MONTH(FTR.DATE_) AS 'AY', DAY(FTR.DATE_) AS 'GÜN',
CR.CODE AS 'CARI_KOD',
MLZ.STGRPCODE AS 'GRUP_KODU',
CONVERT(varchar,MLZ.CODE) AS 'URUN_KODU',MLZ.NAME AS 'URUN_ADI',
CASE WHEN HRK.TRCODE IN (2,3) THEN -1 * HRK.AMOUNT 
	ELSE HRK.AMOUNT 
	END AS 'MİKTAR',
BRM.NAME AS 'BİRİM',
HRK.LINENET AS 'TUTAR',
CASE 
	WHEN  HRK.SOURCEINDEX = 0 THEN 'AMBAR ADI 1'
	WHEN  HRK.SOURCEINDEX = 1 THEN 'AMBAR ADI 2'
  --GEÇERLİ AMBARLARINIZI GİREBİLİRSİNİZ. BİR TANE AMBAR VARSA İKİNCİ SATIRI SİLEBİLİRSİNİZ.
	END AS 'AMBAR',
CASE
	WHEN HRK.TRCODE = 2 THEN 'P_İADE'
	WHEN HRK.TRCODE = 3 THEN 'T_İADE'
	WHEN HRK.TRCODE = 7 THEN 'P_SATIS'
	WHEN HRK.TRCODE = 8 THEN 'T_SATIS'
  --PERAKENDE SATIŞ, PERAKENDE İADE, TOPTAN SATIŞ, TOPTAN İADE
END AS 'F_TİPİ'
FROM LG_XXX_STLINE HRK 
INNER JOIN LG_XXX_ITEMS MLZ ON MLZ.LOGICALREF = HRK.STOCKREF
INNER JOIN LG_XXX_INVOICE FTR ON FTR.LOGICALREF = HRK.INVOICEREF
INNER JOIN LG_XXX_CLCARD CR ON HRK.CLIENTREF = CR.LOGICALREF
INNER JOIN LG_XXX_UNITSETF BRM ON BRM.LOGICALREF = HRK.USREF
WHERE HRK.TRCODE IN (2,3,7,8) AND HRK.BILLED = 1 AND HRK.CANCELLED = 0 AND HRK.SOURCEINDEX NOT IN(2) 
---XXX OLAN BÖLÜMLERİ VERİTABANINIZA GÖRE DEĞİŞTİRMENİZ GEREKLİ
